apiVersion: v1
kind: Service

metadata:
  name: triprisk-api
  namespace: triprisk

spec:
  type: ClusterIP

  selector:
    app: triprisk-api

  ports:
    - name: http

      port: 80

      targetPort: http